version: "3.8"

services:
  database:
    image: mysql:latest
    volumes:
      - "mysql_data:/var/lib/mysql"
    container_name: my_diary_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: my_diary_app
    ports:
      - "3000:3000"
    depends_on:
      - database

volumes:
  mysql_data:
